########## How To Use Docker Image ###############
##
##  Image Name: denny/jenkins_image:1.0
##  Git link: https://github.com/DennyZhang/jenkins_image/blob/tag_v1/Dockerfile
##  Docker hub link:
##  Build docker image: time docker build --no-cache -f Dockerfile_v1_0 -t denny/jenkins_image:1.0 --rm=true .
##  Start jenkins: docker run -p 18080:8080 denny/jenkins_image:1.0
##  Description: Manage via Jenkins GUI
##################################################
# Base Docker image: https://hub.docker.com/r/jenkins/jenkins/

FROM jenkins/jenkins:2.84

LABEL maintainer "Denny<https://www.dennyzhang.com/contact>"

# Install thinbackup plugin
user root

# Configure Jenkins java options
# timezone: Asia/Shanghai, America/New_York, America/Los_Angeles
# https://www.epochconverter.com/timezones
ENV JENKINS_TIMEZONE "UTC"

# Run groovy
COPY timezone.groovy /usr/share/jenkins/ref/init.groovy.d/timezone.groovy

# Install jenkins plugins
RUN /usr/local/bin/install-plugins.sh structs:1.8 && \
    ###############################################################
    # Pipeline
    /usr/local/bin/install-plugins.sh bouncycastle-api:2.16.1 && \
    /usr/local/bin/install-plugins.sh pipeline-model-definition:1.1.6 && \
    /usr/local/bin/install-plugins.sh pipeline-graph-analysis:1.4 && \
    /usr/local/bin/install-plugins.sh pipeline-rest-api:2.8 && \
    /usr/local/bin/install-plugins.sh pipeline-stage-view:2.8 && \
    /usr/local/bin/install-plugins.sh pipeline-model-declarative-agent:1.1.1 && \
    /usr/local/bin/install-plugins.sh maven-plugin:2.16 && \
    /usr/local/bin/install-plugins.sh pipeline-stage-tags-metadata:1.1.6 && \
    /usr/local/bin/install-plugins.sh handlebars:1.1.1 && \
    /usr/local/bin/install-plugins.sh pipeline-stage-step:2.2 && \
    /usr/local/bin/install-plugins.sh pipeline-model-extensions:1.1.6 && \
    /usr/local/bin/install-plugins.sh pipeline-milestone-step:1.3.1 && \
    /usr/local/bin/install-plugins.sh workflow-cps-global-lib:2.8 && \
    /usr/local/bin/install-plugins.sh workflow-support:2.14 && \
    /usr/local/bin/install-plugins.sh pipeline-model-api:1.1.6 && \
    /usr/local/bin/install-plugins.sh pipeline-input-step:2.7 && \
    /usr/local/bin/install-plugins.sh pipeline-build-step:2.5 && \
    /usr/local/bin/install-plugins.sh workflow-step-api:2.11 && \
    /usr/local/bin/install-plugins.sh docker-commons:1.7 && \
    /usr/local/bin/install-plugins.sh workflow-durable-task-step:2.12 && \
    /usr/local/bin/install-plugins.sh durable-task:1.14 && \
    /usr/local/bin/install-plugins.sh workflow-basic-steps:2.5 && \
    /usr/local/bin/install-plugins.sh workflow-cps:2.36 && \
    /usr/local/bin/install-plugins.sh workflow-api:2.17 && \
    /usr/local/bin/install-plugins.sh workflow-aggregator:2.5 && \
    ###############################################################
    # https://www.dennyzhang.com/jenkins_benefits
    /usr/local/bin/install-plugins.sh slack:2.2 && \
    /usr/local/bin/install-plugins.sh dashboard-view:2.9.11 && \
    /usr/local/bin/install-plugins.sh timestamper:1.8.8 && \
    /usr/local/bin/install-plugins.sh git:3.3.0 && \
    /usr/local/bin/install-plugins.sh thinBackup:1.9 && \
    /usr/local/bin/install-plugins.sh jobConfigHistory:2.16 && \
    /usr/local/bin/install-plugins.sh build-timeout:1.18 && \
    /usr/local/bin/install-plugins.sh naginator:1.17.2 && \
    /usr/local/bin/install-plugins.sh credentials:2.1.14 && \
    /usr/local/bin/install-plugins.sh plain-credentials:1.4 && \
    /usr/local/bin/install-plugins.sh display-url-api:2.0 && \
    /usr/local/bin/install-plugins.sh junit:1.20 && \
    /usr/local/bin/install-plugins.sh workflow-multibranch:2.15 && \
    /usr/local/bin/install-plugins.sh docker-workflow:1.11 && \
    /usr/local/bin/install-plugins.sh workflow-job:2.11 && \
    /usr/local/bin/install-plugins.sh workflow-scm-step:2.5

user jenkins

WORKDIR /var/jenkins_home
